### PR TITLE
Make this compatible with LS 5.x

### LINKED ISSUE #10: this plugin doesn't work with logstash 5.x
```
[2016-11-02T12:55:06,006][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `terminal' for #<LogStash::Logging::Logger:0x4b720e33>>, :backtrace=>["/tmp/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/logstash-output-exec-3.0.3/lib/logstash/outputs/exec.rb:58:in `receive'", "org/jruby/RubyIO.java:4475:in `popen3'", "/private/tmp/logstash-5.0.0/vendor/jruby/lib/ruby/1.9/open3.rb:74:in `popen3'", "/tmp/logstash-5.0.0/vendor/bundle/jruby/1.9/gems/logstash-output-exec-3.0.3/lib/logstash/outputs/exec.rb:51:in `receive'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:297:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:296:in `output_batch'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:252:in `worker_loop'", "/tmp/logstash-5.0.0/logstash-core/lib/logstash/pipeline.rb:225:in `start_workers'"]}
```

### PR DESCRIPTION
**Pull request by suyograo**
Logging changes in 5.0 broke this plugin. We now use info and debug
to log output of the exec'd commands

Fixes #10

### CODE REVIEW

File: lib/logstash/outputs/exec.rb [hunk 1]
```diff
@@ -50,12 +50,12 @@ def receive(event)
 
     Open3.popen3(cmd) do |stdin, stdout, stderr|
       if @logger.debug?
-        @logger.pipe(stdout => :debug, stderr => :debug)
+        @logger.debug(stdout => :debug, stderr => :debug)
```
Comment (ph) [inline lib/logstash/outputs/exec.rb]: should it be something like this? (I did not test it)

```ruby
 @logger.debug(:stdout => stdout.read, :stderr => stderr.read)
 ```
The stdout and the stderr should be IO object and we need to read them to display the messages.

**Review by ph — CHANGES_REQUESTED** [review]

**Review by ph — APPROVED** [review]

**Comment by ph** [comment]
LGTM
